# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logit_reg_lbfgs <- function(X, y) {
    .Call(`_snpcombineR_logit_reg_lbfgs`, X, y)
}

#' @rdname resample_genotype_data
#' @export
resample_genotype_data <- function(genotype_data, n_resamples) {
    .Call(`_snpcombineR_resample_genotype_data`, genotype_data, n_resamples)
}

#' @rdname simulate_gene_gwas_data
#' @export
simulate_gene_gwas_data <- function(genotype_data, is_non_null, causal_snp_i, causal_or, case_rate) {
    .Call(`_snpcombineR_simulate_gene_gwas_data`, genotype_data, is_non_null, causal_snp_i, causal_or, case_rate)
}

#' @rdname compute_cor_matrix
#' @export
compute_cor_matrix <- function(X) {
    .Call(`_snpcombineR_compute_cor_matrix`, X)
}

#' @rdname compute_chol_matrix
#' @export
compute_chol_matrix <- function(X) {
    .Call(`_snpcombineR_compute_chol_matrix`, X)
}

#' @rdname check_is_pd_cor_matrix
#' @export
check_is_pd_cor_matrix <- function(eig_val, eps) {
    .Call(`_snpcombineR_check_is_pd_cor_matrix`, eig_val, eps)
}

#' @rdname make_pd_cor_matrix
#' @export
make_pd_cor_matrix <- function(cor_matrix, eig_val, eig_vec, eps) {
    .Call(`_snpcombineR_make_pd_cor_matrix`, cor_matrix, eig_val, eig_vec, eps)
}

#' @rdname force_pd_cor_matrix
#' @export
force_pd_cor_matrix <- function(cor_matrix, eps) {
    .Call(`_snpcombineR_force_pd_cor_matrix`, cor_matrix, eps)
}

#' @rdname compute_chol_cor_matrix
#' @export
compute_chol_cor_matrix <- function(cor_matrix, eps) {
    .Call(`_snpcombineR_compute_chol_cor_matrix`, cor_matrix, eps)
}

#' @rdname compute_brown_cov_sum
#' @export
compute_brown_cov_sum <- function(genotype_cor_mat) {
    .Call(`_snpcombineR_compute_brown_cov_sum`, genotype_cor_mat)
}

#' @rdname compute_two_sided_cov_sum
#' @export
compute_two_sided_cov_sum <- function(genotype_cor_mat) {
    .Call(`_snpcombineR_compute_two_sided_cov_sum`, genotype_cor_mat)
}

#' @rdname compute_magma
#' @export
compute_magma <- function(snp_pvals, genotype_cor_mat) {
    .Call(`_snpcombineR_compute_magma`, snp_pvals, genotype_cor_mat)
}

#' @rdname compute_browns
#' @export
compute_browns <- function(snp_pvals, genotype_cor_mat, two_sided) {
    .Call(`_snpcombineR_compute_browns`, snp_pvals, genotype_cor_mat, two_sided)
}

#' @rdname compute_sim_pvals
#' @export
compute_sim_pvals <- function(snp_pvals, snp_zstats, genotype_cor_mat, n_blocks, block_size, eps) {
    .Call(`_snpcombineR_compute_sim_pvals`, snp_pvals, snp_zstats, genotype_cor_mat, n_blocks, block_size, eps)
}

#' @rdname compute_gene_level_test
#' @export
compute_gene_level_test <- function(snp_pvals, snp_zstats, genotype_data, sim_n_blocks, sim_block_size, eps) {
    .Call(`_snpcombineR_compute_gene_level_test`, snp_pvals, snp_zstats, genotype_data, sim_n_blocks, sim_block_size, eps)
}

#' @rdname simulate_gene_level_stats
#' @export
simulate_gene_level_stats <- function(init_genotype_data, resample, n_resamples, is_non_null, causal_snp_i, causal_or, case_rate, sim_n_blocks, sim_block_size, eps) {
    .Call(`_snpcombineR_simulate_gene_level_stats`, init_genotype_data, resample, n_resamples, is_non_null, causal_snp_i, causal_or, case_rate, sim_n_blocks, sim_block_size, eps)
}

#' @rdname generate_sim_truth_data
#' @export
generate_sim_truth_data <- function(genotype_cor_matrix, n_blocks, block_size, eps) {
    .Call(`_snpcombineR_generate_sim_truth_data`, genotype_cor_matrix, n_blocks, block_size, eps)
}

#' @rdname compute_fixed_sim_pvals
#' @export
compute_fixed_sim_pvals <- function(snp_pvals, snp_zstats, sim_truth_matrix) {
    .Call(`_snpcombineR_compute_fixed_sim_pvals`, snp_pvals, snp_zstats, sim_truth_matrix)
}

#' @rdname compute_fixed_gene_level_test
#' @export
compute_fixed_gene_level_test <- function(sim_gwas_data, sim_truth_matrix, genotype_cor_matrix) {
    .Call(`_snpcombineR_compute_fixed_gene_level_test`, sim_gwas_data, sim_truth_matrix, genotype_cor_matrix)
}

#' @rdname fixed_cor_gene_test_sim
#' @export
fixed_cor_gene_test_sim <- function(genotype_data, genotype_cor_matrix, n_gene_sims, is_non_null, causal_snp_i, causal_or, case_rate, truth_sim_n_blocks, truth_sim_block_size, n_cores, eps) {
    .Call(`_snpcombineR_fixed_cor_gene_test_sim`, genotype_data, genotype_cor_matrix, n_gene_sims, is_non_null, causal_snp_i, causal_or, case_rate, truth_sim_n_blocks, truth_sim_block_size, n_cores, eps)
}

